USE [MSSqlProfWeb30]
GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeProfessori] ON 
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 389, N'Aguzzoni Bettina', N'bettina.aguzzoni@gmail.com', N'3286783538', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 2, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 410, N'Amadori Mario', N'mario.amadori67@gmail.com', N'3737653127', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 409, N'Baldacci Marco', N'mac358@hotmail.it', N'3348585914', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 429, N'Bianchi Elena', N'test53@valeriomcse.eu', N'3477945457', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 398, N'Bianchini Daniela', N'bdaniela@libero.it', N'3339165923', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 388, N'Biotti Bruno', N'bbiotti@gmail.com', N'3484749307', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 2, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 387, N'Botticelli Sondra', N'sondrabotticelli@gmail.com', N'3287431145', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 379, N'Brici Barbara', N'bbpetronilla@gmail.com', N'3331244031', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 380, N'Bruschi Cristina', N'cribru52@gmail.com', N'3298132208', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 420, N'Camanzi Sara', N'saracamanzi@libero.it', N'3482370357', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 394, N'Casali Alder', N'aldercasali@tin.it', N'3474647101', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 430, N'Celli Ada', N'test54@valeriomcse.eu', N'3295484539', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 422, N'Cesaretti Alberto', N'test46@valeriomcse.eu', N'3393449207', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 414, N'Correggioli Paolo', N'paolocorreggioli@libero.it', N'3356438284', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 412, N'De Luigi Milena', N'milenalu01@gmail.com', N'3291658211', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 423, N'De Marchi Sara', N'test47@valeriomcse.eu', N'3343797360', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 383, N'De Marini Luisa', N'luisademarini@libero.it', N'3493604489', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 378, N'Donati Daniela', N'daniela@donatialoque.it', N'3290912427', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 2, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 400, N'Donati Daniele', N'daniele.donati.it@gmail.com', N'3208457214', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 421, N'Drudi Serafino', N'sdrudi@hotmail.it', N'3356660705', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 403, N'Farina Federica', N'fedifarina1@gmail.com', N'3313449261', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 395, N'Fiori Barbara', N'almularoni@libero.it', N'3396118742', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 396, N'Flamigni Angela', N'angela@promozionealberghiera.it', N'3479613988', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 424, N'Forlani Beatrice', N'test48@valeriomcse.eu', N'3807384203', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 406, N'Fratta Giusi', N'giusfra54@hotmail.it', N'3475242587', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 413, N'Gabrielli Orlando', N'orlando.gabrielli@gmail.com', N'339657042', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 419, N'Gasperoni Rosanna', N'rossgian15@gmail.com', N'3356140679', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 418, N'Genghini Rosa Ana', N'rosannagenghini@gmail.com', N'3355486174', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 405, N'Giavolucci  Gabriella', N'ggiavolucci@gmail.com', N'3381579226', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 417, N'Giunta Roberto', N'roberto.giunta.1970@gmail.com', N'3358118564', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 390, N'Gregori Isella', N'isellagregori@libero.it', N'3393642455', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 2, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 385, N'Grossi Paola', N'paolagrossi@inwind.it', N'3393345099', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 399, N'Grotti Claudio', N'claudio.grotti@hotmail.it', N'3358343942', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 382, N'Grotti Daniela', N'danigrotti2@gmail.com', N'3337517532', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 407, N'Lazzari Maria Letizia', N'laleti@ymail.com', N'3397779548', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 393, N'Librari Amelia', N'a.librari@virgilio.it', N'3497379701', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 408, N'Lodovico luca', N'lodovico.luca@gmail.com', N'3389542463', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 425, N'Mancini Emilio', N'test49@valeriomcse.eu', N'541770520', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 392, N'Marinucci Dina', N'marinuccidina@yaooh.it', N'3482442577', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 2, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 384, N'Mariotti Alfiero', N'mariotti.alfiero@gmail.com', N'3202360000', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 415, N'Mehdi Shkreli', N'profmedi@libero.it', N'3337505378', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 426, N'Nucci Tiziana', N'test50@valeriomcse.eu', N'3401555945', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 431, N'Orlandi Donatella', N'test55@valeriomcse.eu', N'3204563605', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 404, N'Pacelli Francesco', N'fpacelli97@gmail.com', N'3311208604', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 427, N'Paparella Alessandra', N'test51@valeriomcse.eu', N'3401497224', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 402, N'Pari Pierluigi', N'drppari@libero.it ', N'3482762770', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 386, N'Pradarelli Paolo', N'prpir@tiscali.it', N'3383443043', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 391, N'Romani Catia', N'romanicatia@gmail.com', N'3397029056', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 2, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 381, N'Seguiti Cristina', N'cristinaseguiti@yaooh.it', N'3355301466', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 1, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 411, N'Tamburini Marta', N'martatamburini@hotmail.com', N'3472663464', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 428, N'Tamburini Paolo', N'test52@valeriomcse.eu', N'3341636543', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 416, N'Tonti Raffaella', N'raffaellatonti62@gmai.com', N'91', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 401, N'Verardo Daniele', N'danilicercatore@libero.it', N'3389709021', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 2, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 397, N'Zamagni Barbara', N'barbarazamagni@virgiglio.it', N'3283793014', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 1, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (16, 432, N'Zangoli Giovanni Battista', N'test56@valeriomcse.eu', N'3894478426', N'0', NULL, N'RIMINI', N'RN', N'47921', NULL, NULL, CAST(N'2020-08-23' AS Date), CAST(N'2020-08-23' AS Date), NULL, NULL, 3, 3, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-08-23' AS Date))
GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeProfessori] OFF
GO
