
SET IDENTITY_INSERT [dbo].[pf_anagrafeProfessori] ON 
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 281, N'Astori  Antonietta', N'astorianto@gmail.com', N'035 301801', N'338 6951280', N'via Isonzo 2', N'Seriate', N'XX', N'24068', N'STRNNT51C67D352X', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Dossena', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 282, N'Baldissin Armando', N'arma.baldi@gmail.com', N'035', N'338 9360462', N'via Martiri di Cefalonia 3', N'Bergamo', N'XX', N'24121', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Milano', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 283, N'Bassanelli Pierluigi', N'pgbassanelli@gmail.com', N'035 577088', N'348 7667228', N'via Martiri d.libertà 14', N'Sorisole', N'XX', N'24010', N'BSSPLG48B13G863N', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Ponteranica', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 284, N'Beneduci Gianfranco', N'gianfranco.beneduci@yahoo.it', N'035 664390', N'320 7935543', N'via Marconi 20', N'Gorle', N'XX', N'0', N'BNDGFR72E20L219V', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Torino', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 285, N'Beretta Chiara', N'chiaraberry1004@gmail.com', N'035', N'348 6622834', N'via Doppoli 30', N'Zandobbio', N'XX', N'0', N'BRTCHR01P60I628T', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Seriate', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 286, N'Bombardieri  Angela', N'bombardieriangela@hotmail.it', N'035 213381', N'333 4206793', N'via f.lli Bronzetti 4', N'Bergamo', N'XX', N'24124', N'BMBNGL50T69D905M', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Gandino', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 287, N'Chitarrari Graziella', N'gabriellachitarrari@gmail.com', N'035 218312', N'333 6850015', N'via Borgo Palazzo 90', N'Bergamo', N'XX', N'24125', N'CHTGZL42M66G424M', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Pellegrino Parmense', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 288, N'Costantini Rita', N'rtcostantini@gmail.com', N'035', N'340 7920592', N'piazza Alberico da Rosciate ', N'Scanzorosciate', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Treviglio', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 289, N'Cristofoletto Valentino', N'v.cristofoletto@gmail.com', N'035 246444', N'392 3379266', N'via Suardi 7', N'Bergamo', N'XX', N'24124', N'CRSCNT41R03M163O', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Zenson di piave', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 290, N'Crotti Loretta', N'lorettacrotti@yahoo.it', N'035', N'347 8817597', N'via Franzarola 8', N'Bergamo', N'XX', N'24124', N'CRTLTT65A53A962P', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bonate Sotto', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 291, N'Crotti Mario', N'croma4148@libero.it', N'035 242347', N'349 2877195', N'via F.lli Calvi 10/E', N'Bergamo', N'XX', N'24122', N'CRTMRA41H27B703X', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Crespi d''Adda', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 292, N'Finatti Julia', N'julinhafinatti@gmail.com', N'035', N'351 9051145', N'via Duse 8', N'Sant’Omobono', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Brasile', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 293, N'Ghilardi Giulia', N'giulia4101@gmail.com', N'035', N'350 5437332', N'via Vittoria 11', N'Nembro', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Seriate', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 294, N'Giacomoni Remo', N'remog2020@gmail.com', N'035 270624', N'349 2951337', N'via Garibaldi 4', N'Bergamo', N'XX', N'24122', N'GCMRME33A19D969C', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Genova', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 295, N'Guccio Filippa', N'filippaguccio@libero.it', N'035 259723', N'348 5068212', N'via Goethe 92', N'Bergamo', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Piazza Almerina', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 296, N'Innocenti Mariangela', N'maurialberti@alice.it', N'035 313264', N'348 2840007', N'via Manzoni 4/B', N'Orio al Serio', N'XX', N'24050', N'NNCMNG52A63A794K', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 297, N'Liverani Antonio', N'antonio_liverani@libero.it', N'035 317757', N'347 3079106', N'via dei Carpinoni 25 ', N'Bergamo', N'XX', N'24126', N'LVRNDR45S12D458I', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Faenza', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 299, N'Locatelli Maria Cristina', N'mcri.locatelli@gmail.com', N'035 241940', N'349 2357502', N'via Martiri di Cefalonia 3', N'Bergamo', N'XX', N'0', N'LCTMCR61M48A794Q', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 298, N'Luciani Rosaria', N'rosarialuciani@gmail.com', N'035', N'328 0653578', N'via Calabria 2', N'Rieti', N'XX', N'2100', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Rieti', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 300, N'Masserini Mario', N'masserini1@libero.it', N'035', N'338 6249030', N'via Reich 68/D', N'Torre Boldone', N'XX', N'24020', N'MSSMRA67S02D952K', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Gazzaniga', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 301, N'Morali Patrizia', N'patrizia.morali@ibero.it', N'035 255084', N'349 5337593', N'via D’Annunzio 19', N'Bergamo', N'XX', N'24128', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 302, N'Moretti Roberta', N'moretti.corsi@yahoo.it', N'035', N'335 5719139', N'via Previtali 20', N'Bergamo', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 303, N'Mugerli Marina suor', N'm.mugerli@tiscali.it', N'035 4243736', N'346 4928770', N'via Caldara 4', N'Bergamo', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Rho', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 304, N'Paganini Vanda', N'vandapaganini@gmail.com', N'035', N'339 6329368', N'via Martiri di Cefalonia 3', N'Bergamo', N'XX', N'24121', N'PGNVND57M69E463I', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'La Spezia', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 305, N'Pellerano Claudia', N'pellerano@fastwebnet.it', N'035 330163', N'349 5631831', N'via autostrada 3', N'Bergamo', N'XX', N'24126', N'PLLCLD58E47H183W', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Rapallo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 306, N'Pelliccioli Enrico', N'enripelli@libero.it', N'035', N'339 5710713', N'via Nullo 17', N'Seriate', N'XX', N'24058', N'PLLNRC46S13A246W', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Alzano Lombardo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 307, N'Pesenti Agnese', N'pesentiagnese@gmail.com', N'035 248416', N'348 8804895', N'via Martiri di Cefalonia 3', N'Bergamo', N'XX', N'0', N'PSNGNS46P53L388E', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Trescore Terme', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 308, N'Poli Gabriella', N'polo.gabriella00@gmail.com', N'035 345287', N'328 9030433', N'Via', N'Bergamo', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'italia', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 309, N'Riva  Rosa', N'riva_rosa@hotmail.com', N'035 297922', N'347 3246760', N'via Paci 8', N'Bergamo', N'XX', N'24125', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 310, N'Romano Imma', N'immaromano63@yahoo.it', N'035', N'', N'Via', N'Bergamo', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'italia', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 311, N'Rovelli Anna', N'anna.rovellii@tiscali.it', N'035', N'347 3551663', N'via Baccarello 16', N'Terno d’Isola', N'XX', N'0', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 312, N'Sala  Miranda', N'salamiranda49@gmail.com', N'035 257089', N'349 6641222', N'via Longuelo 61', N'Bergamo', N'XX', N'24129', N'SLAMND49D67F864Q', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Nembro', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 313, N'Sciarretta Giuseppe', N'giuseppe.sciarretta@teletu.it', N'035 217600', N'334 3969496', N'via Borgo Palazzo 90', N'Bergamo', N'XX', N'24125', N'SCRGPP41M11L334B', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Trasacco', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 314, N'Serio Emma', N'emy.serio@tiscali.it', N'035', N'333 5808196', N'via S.Antonino 4', N'Bergamo', N'XX', N'24122', N'SREMME50S52F205A', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'MI', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 315, N'Stigliani Giuseppe Vincenzo', N'giustigi@libero.it', N'035 2650586', N'320 2342931', N'via Ghislandi 33', N'BuonosAires', N'XX', N'24125', N'STGGPP62M05Z600D', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'italia', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 316, N'Tironi Rita', N'iratirinto@hotmail.it', N'035 0346804', N'344 0121552', N'via Tobagi 26', N'Bergamo', N'XX', N'24127', N'TRNRTI49B56A794H', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 317, N'Tironi Vittorio', N'tironi_v@alice.it', N'035 540517', N'339 6022153', N'viale De Gasperi 17', N'Almenno S.B.', N'XX', N'24030', N'TRNVTR42E19D215L', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Curno', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 318, N'Vallar Valerio', N'studio.vallar@tiscalinet.it', N'035 213349', N'335 237486', N'via S.Giorgio 17', N'Bergamo', N'XX', N'24122', N'VLLVRL35T08Z129E', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bucarest', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 319, N'Vignati Massimo', N'mass.vign@gmail.com', N'035 203462', N'348 9032630', N'via dei Tigli 103', N'Treviolo', N'XX', N'24048', N'VGNMSM49C25L682T', NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Varese', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (15, 320, N'Zanchi Ferdinando', N'ferdinando.zanchi@fastwebnet.it', N'035 251687', N'339 1331971', N'via Coghetti 274', N'Bergamo', N'XX', N'24128', NULL, NULL, CAST(N'2020-07-30' AS Date), CAST(N'2020-07-30' AS Date), NULL, N'Bergamo', 0, 0, 0, 0, 0, 0, NULL, 0, 0, N'0', NULL, NULL, N'0.0', CAST(N'2020-07-30' AS Date))
GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeProfessori] OFF
GO
