--USE [MSSqlProfWeb30]
--GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeStudenti] ON 

INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 591, N'ABDELLI ANNA', N'TEST89@GMAIL.COM', CAST(N'1900-01-01' AS Date), N'', N'', N'', N'VIA AMATI 38', N'RIMINI', N'RN', N'21100', N'000', N'3896026953', 0, N'1', 0, N'SOSTEGNO - ITALIANA -', CAST(N'2019-12-11' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, CAST(N'1900-01-01' AS Date), 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 592, N'ALLEGRINI MARTA', N'test60@gmail.com', NULL, NULL, NULL, NULL, N'VIA CROCE DEL SUD 22', N'BOLOGNA', NULL, NULL, N'3270766655', N'3355712132', 0, N'4', 0, N'BES - ITALIANA - roberta-marzi@fastweb.it', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 593, N'ANGOTTI MARIALUCE', N'marialuce@gmail.com', NULL, NULL, NULL, NULL, N'VIA SALA 88', N'RIMINI', NULL, NULL, N'3279572673', N'3482216868', 0, N'5', 0, N'DSA - ITALIANA - ', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 594, N'ANTONACCI STEFANO', N'antonaccistefano142@gmail.com', NULL, NULL, NULL, NULL, N'VIA PLEADI 13', N'RIMINI', NULL, NULL, N'3338116512', N'3479831753', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2020-01-29' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 595, N'ASTOLFI PENELOPE', N'penny.astolfi@icloud.com', NULL, NULL, NULL, NULL, N'VIA MOLTABANO 16', N'RIMINI', NULL, NULL, N'3246218163', N'335283815', 0, N'3', 0, N'ritirata - ITALIANA - ', CAST(N'2020-01-24' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 596, N'ASTOLFI TOMMASO', N'test96@gmail.com', NULL, NULL, NULL, NULL, N'VICOLO SAN GIOVANNI 10', N'RIMINI', NULL, NULL, N'366109449', N'3391916671', 0, N'1', 0, N' - ITALIANA - ', CAST(N'2020-01-22' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 597, N'BAHRI YASSINE', N'test49@gmail.com', NULL, NULL, NULL, NULL, N'VIA CASADEI 44', N'RIMINI', NULL, NULL, N'3458310921', N'377947947', 0, N'3', 0, N'SOSTEGNO - ITAL/TUNISINA - ', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 598, N'BAKAYOKO FATIME ROXANE', N'test85@gmail.com', NULL, NULL, NULL, NULL, N'VIA EMILIA 312', N'RIMINI', NULL, NULL, N'3278389310', N'3881475424', 0, N'1', 0, N'S SECONDA - ITALIANA - ', CAST(N'2019-11-29' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 599, N'BARABESI GABRIEL FRANCO', N'gabriel23basabesi@gmail.com', NULL, NULL, NULL, NULL, N'VIA NORBERTO PAZZINI 6', N'VERUCCHIO', NULL, NULL, N'3425527166', N'3334276018', 0, N'2', 0, N'S SECONDA - ITALIANA - ', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 600, N'BARILLARI CAMILLA', N'test107@gmail.com', NULL, NULL, NULL, NULL, N'VIA ARNO 53', N'RIMINI', NULL, NULL, N'3661861821', N'3383066186', 0, N'2', 0, N' - ITALIANA - ', CAST(N'2020-02-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 601, N'BASTIANINI LUCIA', N'lucia2004b@gmail.com', NULL, NULL, NULL, NULL, N'VIA OVIDIO 11', N'RIMINI', NULL, NULL, N'3341907010', N'3382337028', 0, N'2', 0, N' - ITALIANA - micolmorri@gmail.com', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 602, N'BATTAGLI MARTA', N'test67@gmail.com', NULL, NULL, NULL, NULL, N'VIA ALESSANDRINI 4', N'RIMINI', NULL, NULL, N'3917689241', N'3288677425', 0, N'2', 0, N' - ITALIANA - ', CAST(N'2019-10-28' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 603, N'BELLANDI ELISA ILENIA', N'elisabellandii@gmail.com', NULL, NULL, NULL, NULL, N'VIA COPPI N6', N'RIMINI', NULL, NULL, N'3343091204', N'000', 0, N'5', 0, N' - ITALIANA - ', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 604, N'BERLINI ANNA ZENO', N'annab9112001@gmail.com', NULL, NULL, NULL, NULL, N'VIA POMPOSA 5', N'RIMINI', NULL, NULL, N'3403308474', N'3896761981', 0, N'5', 0, N'BES - ITALIANA - sabrinabersani@gmail.com', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 605, N'BERNADINI LARA', N'bernadinilara@gmail.com', NULL, NULL, NULL, NULL, N'VIA VERONA 3', N'RIMINI', NULL, NULL, N'3493914478', N'3911184584', 0, N'5', 0, N' - ITALIANA - ', CAST(N'2019-10-28' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 606, N'BERTANI VALENTINA', N'valebertani2004@gmail.com', NULL, NULL, NULL, NULL, N'VIA DUCALE 19', N'RIMINI', NULL, NULL, N'3913543051', N'3397295274', 0, N'2', 0, N' - ITALIANA - poggioli.cinzia@gmail.com', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 607, N'BEVITORI CHIARA', N'test62@gmail.com', NULL, NULL, NULL, NULL, N'VIA CAGNI 70', N'RIMINI', NULL, NULL, N'35166599', N'3338289667', 0, N'3', 0, N'SOSTEGNO - ITALIANA - ', CAST(N'2019-10-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 608, N'BEZZI VIOLA', N'test100@gmail.com', NULL, NULL, NULL, NULL, N'VIA FENICE 25', N'RIMIINI', NULL, NULL, N'3465764003', N'000', 0, N'5', 0, N' - ITALIANA - ', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 609, N'BIANCUCCI GIULIA', N'test65@gmail.com', NULL, NULL, NULL, NULL, N'VIA GIACOMO LEOPARDI 23', N'RIMINI', NULL, NULL, N'3200707567', N'3458389590', 0, N'2', 0, N' - ITALIANA - salasilvana5@gmail.com', CAST(N'2019-10-24' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 610, N'BONIFAZI SARA', N'test102@gmail.com', NULL, NULL, NULL, NULL, N'VIA PRADESE 39E', N'RIMINI', NULL, NULL, N'3332494510', N'3497074774', 0, N'4', 0, N' - ITALIANA - barilla72@hotmail.com', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 611, N'BORS VLADISLAV', N'test84@gmail.com', NULL, NULL, NULL, NULL, N'VIA ADOLFO ALBERTAZZI 15', N'RIMINI', NULL, NULL, N'3200134383', N'000', 0, N'4', 0, N'STRANIERO ono - MOLDAVA - ', CAST(N'2019-11-28' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 612, N'BRONZETTI ALICE', N'alice.ghina@gmail.com', NULL, NULL, NULL, NULL, N'VIA NANNI 28', N'RIMINI', NULL, NULL, N'37553377', N'3270886346', 0, N'5', 0, N' - ITALIANA - biffy64@alice.it', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 613, N'BUGLI NICOLA', N'test82@gmail.com', NULL, NULL, NULL, NULL, N'VIA DELLA CARLETTA 10', N'RIMINI', NULL, NULL, N'3384908085', N'3385005019', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2019-11-27' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 614, N'CAMBRIA GIULIA', N'giulia cambria@gmail.com', NULL, NULL, NULL, NULL, N'VIA DAOLIO 34', N'RIMINI', NULL, NULL, N'3247929122', N'3497362336', 0, N'2', 0, N' - ITALIANA - ', CAST(N'2019-12-13' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 615, N'CARLI ANNA ', N'test72@gmail.com', NULL, NULL, NULL, NULL, N'VIA DI DUCCIO 1', N'RIMINI', NULL, NULL, N'3348776288', N'3351485520', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2019-11-07' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 616, N'CELLI MARTINA', N'arimars@libero.it', NULL, NULL, NULL, NULL, N'VIA MILAZZO 45', N'RIMINI', NULL, NULL, N'3755592690', N'3342080615', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2019-11-19' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 617, N'CESARI MELISSA', N'melissa cesari106@gmail.com', NULL, NULL, NULL, NULL, N'VIA DELLE PIANTE3 ', N'RIMINI', NULL, NULL, N'3703348569', N'3311186423', 0, N'4', 0, N'DSA - ITALIANA - ', CAST(N'2019-10-22' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 618, N'CHIARI GABRIELE', N'test86@gmail.com', NULL, NULL, NULL, NULL, N'VIA LIBIA 15', N'RIMINI', NULL, NULL, N'3356001098', N'3356001098', 0, N'1', 0, N' - ITALIANA - ', CAST(N'2019-11-29' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 619, N'CHIBA AMIR', N'test79@gmail.com', NULL, NULL, NULL, NULL, N'VIA A.ABETTI 9', N'RIMINI', NULL, NULL, N'3247808506', N'3397526540', 0, N'3', 0, N'S SECONDA - ITALO-TUNISINO - ', CAST(N'2019-11-21' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 620, N'CIANCI CRISTINA', N'test61@gmail.com', NULL, NULL, NULL, NULL, N'VIA SAN LEO 2', N'RIMINI', NULL, NULL, N'3343199675', N'3332572147', 0, N'1', 0, N' - ITALIANA - ', CAST(N'2019-10-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 621, N'CICORIA GIULIA ', N'test81@gmail.com', NULL, NULL, NULL, NULL, N'VIA ABBA 3', N'RIMINI', NULL, NULL, N'3339370677', N'3339370677', 0, N'2', 0, N' - ITALIANA  - ', CAST(N'2029-11-25' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 622, N'CLEMENTI LAVINIA ', N'test80@gmail.com', NULL, NULL, NULL, NULL, N'VIA VICO 10', N'RIMINI', NULL, NULL, N'3479134462', N'000', 0, N'4', 0, N' - ITALIANA  - ', CAST(N'2019-11-22' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 623, N'COMANDINI MARCO', N'test58@gmail.com', NULL, NULL, NULL, NULL, N'VIA TURCHETTA  82C', N'RIMINI', NULL, NULL, N'3240528717', N'000', 0, N'4', 0, N'DSA -  - ', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 624, N'D''AGOSTINO OMAR ', N'omardagostino@gmail.com ', NULL, NULL, NULL, NULL, N'VIA DEL CIGNO 54', N'RIMINI', NULL, NULL, N'3892913209', N'3201426455', 0, N'4', 0, N' - ITALIANA  - alessiagines1977@gmail.com ', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 625, N'DAL PIAZ GIORGIA BLU', N'test105@gmail.com', NULL, NULL, NULL, NULL, N'VIA T GULLI 28', N'RIMINI', NULL, NULL, N'3274058050', N'3383843384', 0, N'2', 0, N' - ITALIANA - ', CAST(N'2020-02-03' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 626, N'DANESE EMANUELE', N'emauele.danesi@email.it', NULL, NULL, NULL, NULL, N'VIA MACANNO 22', N'RIMINI', NULL, NULL, N'330548461', N'000', 0, N'5', 0, N'SOSTEGNO - ITALIANA - ', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 627, N'DE LUCA SOPHIA', N'dlacg65@alice,it', NULL, NULL, NULL, NULL, N'PORTOVENERE 26', N'RICCIONE', NULL, NULL, N'3925974614', N'3471274392', 0, N'1', 0, N' - ITALIANA - dlacg65@alice.it', CAST(N'2020-01-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 628, N'DE VINCENTIIS PAOLO', N'test55@gmail.com', NULL, NULL, NULL, NULL, N'VIA TELESIO 5', N'RIMINI', NULL, NULL, N'000', N'000', 0, N'5', 0, N'AFFIDO - ITALIANA - ', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 629, N'DELLA BALDA LUCREZIA', N'test92@gmail.com', NULL, NULL, NULL, NULL, N'VIA RANCO 54', N'SAN MARINO', NULL, NULL, N'3662299588', N'3357242153', 0, N'2', 0, N'DSA - STRANIERO - ', CAST(N'2019-12-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 630, N'DI SARNO LUCIA', N'luciadisarno1976@gmail.com', NULL, NULL, NULL, NULL, N'VIA ADIMARI 6', N'RIMIINI', NULL, NULL, N'3273396931', N'3347239037', 0, N'2', 0, N' - ITALIANA - francadidona73@libero.itr', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 631, N'FABBRI ALICE', N'test66@gmail.com', NULL, NULL, NULL, NULL, N'VIA MONTESCUDO 90', N'RIMINI', NULL, NULL, N'3703461040', N'3333036013', 0, N'2', 0, N'DSA - ITALIANA - ', CAST(N'2019-10-25' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 632, N'FABBRI FABIO ', N'test71@gmail.com', NULL, NULL, NULL, NULL, N'VIA BASTIONI ORIENTALI 82', N'RIMINI', NULL, NULL, N'3703378475', N'3471529673', 0, N'2', 0, N' - ITALIANA  - valeana68@gmail.com', CAST(N'2019-11-07' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 633, N'FANTINI GIACOMO', N'test53@gmail.com', NULL, NULL, NULL, NULL, N'VIA RAGANELLA 9', N'RIMINI', NULL, NULL, N'3518805565', N'3293491593', 0, N'2', 0, N' - ITALIANA - elisabetta.fabbri2@auslromagna.it', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 634, N'FESTA DAVIDE DANIELE', N'festadavidedaniele@gmail.com     RIMINI', NULL, NULL, NULL, NULL, N'VIA AS. GARIBALDI 20', N'RIMINI', NULL, NULL, N'3889523149', N'3482838483', 0, N'1', 0, N' - ITALIANA - patriziaspagnuolo4@gmail.com', CAST(N'2019-11-06' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 635, N'FILIPPINI MATTEO', N'test76@gmail.com', NULL, NULL, NULL, NULL, N'VIA SAN CANDIDO 1', N'RIMINI', NULL, NULL, N'3911206929', N'3338361761', 0, N'1', 0, N' - ITALIANA  - ', CAST(N'2019-11-14' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 636, N'GALLI MICHELE', N'michelega@gmail.com', NULL, NULL, NULL, NULL, N'LARGO BORDONI 3', N'RIMINI', NULL, NULL, N'3349690832', N'3492187205', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2019-11-27' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 637, N'GIALLATINI LUCA', N'test56@gmail.com', NULL, NULL, NULL, NULL, N'VIA MACERI 28', N'RIMINI', NULL, NULL, N'3468504208', N'3496420206', 0, N'5', 0, N'DSA - ITALIANA - ', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 638, N'GIANNINI MASSIMO', N'test73@gmail.com', NULL, NULL, NULL, NULL, N'indirizzo', N'SAVIGNANO', NULL, NULL, N'3515390100', N'3292325742', 0, N'1', 0, N'DSA - ITALIANA - ', CAST(N'2019-11-11' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 639, N'GIORGI FEDERICA', N'fede2004.giorgi@gmail.com', NULL, NULL, NULL, NULL, N'VIA DARIO CAMPANA 79', N'RIMINI', NULL, NULL, N'3703194443', N'3393307723', 0, N'2', 0, N' - ITALIANA - acanarecci@libero.it', CAST(N'2019-10-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 640, N'GIULIANELLI ROSA', N'test51@gmail.com', NULL, NULL, NULL, NULL, N'VIA CALATAFINI 28', N'RIMINI', NULL, NULL, N'3343424002', N'3397012434', 0, N'2', 0, N' - ITALIANA - ', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 641, N'GIUNTA FRANCESCO', N'franz04.giunta@gmal.com', NULL, NULL, NULL, NULL, N'VIA CRISPI 89', N'RIMINI', NULL, NULL, N'3278393722', N'3393241129', 0, N'5', 0, N' - ITALIANA - angela.fornasari@email.it', CAST(N'2019-10-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 642, N'GUANIELI ANGELICA', N'test77@gmail.com', NULL, NULL, NULL, NULL, N'indirizzo', N'RIMINI', NULL, NULL, N'000', N'000', 0, N'3', 0, N'DSA -  - ', CAST(N'2019-11-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 643, N'GUERRA SOFIA', N'test54@gmail.com', NULL, NULL, NULL, NULL, N'VIA DEL BIANCOSPINO 4', N'RIMINI', NULL, NULL, N'3668735227', N'3289048405', 0, N'1', 0, N' - ITALIANA - astolficinzia77@gmail.com', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 644, N'GUIDI PIETRO ', N'momigui@libero.it', NULL, NULL, NULL, NULL, N'VIA XXIII SETTEMBRE 125', N'RIMINI', NULL, NULL, N'3394923394', N'3357078098', 0, N'3', 0, N' - ITALIANO - almaluca@alice.it', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 645, N'ISAH TRACY', N'test75@gmail.com', NULL, NULL, NULL, NULL, N'VIA CIRENE 52', N'RIMINI', NULL, NULL, N'3500393851', N'000', 0, N'4', 0, N'STRANIERO grave situazione - NIGERIANA - ', CAST(N'2019-11-13' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 646, N'JEBALI SIOUAR', N'siouaur.jebali@gmail.com', NULL, NULL, NULL, NULL, N'VIA MARIO CAPELLI 3', N'RIMINI', NULL, NULL, N'329989684', N'3332467115', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2019-12-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 647, N'JULIEN BRIGHI LEONARDO', N'leonardo-tbrighi@icloud.com', NULL, NULL, NULL, NULL, N'VIA BAGLI 69', N'RIMINI', NULL, NULL, N'3392511111', N'3314373111', 0, N'2', 0, N'DSA - ITALIANA - ', CAST(N'2020-01-21' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 648, N'KOCEKU ALEKSANDROS', N'test95@gmail.com', NULL, NULL, NULL, NULL, N'VIA ABRUZZO 11', N'RIMINI', NULL, NULL, N'3240853290', N'000', 0, N'1', 0, N' - ALBANESE - ', CAST(N'2020-01-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 649, N'LAORETTA NOEMI', N'test106@gmail.com', NULL, NULL, NULL, NULL, N'VIA CA'' MONTAGNOLO 20', N'MONTESCUDO', NULL, NULL, N'3665329818', N'3331059580', 0, N'1', 0, N'BES - ITALIANA - giusysab@gmail.com', CAST(N'2020-02-13' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 650, N'LOMBARDI KATRIN', N'test101@gmail.com', NULL, NULL, NULL, NULL, N'VIA GIACOMETTI 36', N'RIMINI', NULL, NULL, N'3272580992', N'000', 0, N'5', 0, N' - ITALIANA - ', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 651, N'LUTI ANDREA ', N'andrea01rn@gmail.com', NULL, NULL, NULL, NULL, N'VIA VENDEMINI 9', N'RIMINI', NULL, NULL, N'3913638648', N'000', 0, N'5', 0, N' - ITALIANA  - ', CAST(N'2019-11-04' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 652, N'MAGLI DAVIDE ', N'test68@gmail.com', NULL, NULL, NULL, NULL, N'VIA PORDENONE 1', N'RIMINI', NULL, NULL, N'3899112074', N'3339967415', 0, N'4', 0, N' - ITALIANA - gigimagli@gmail.com', CAST(N'2019-11-05' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 653, N'MAMANI QUISPE CESAR', N'test63@gmail.com', NULL, NULL, NULL, NULL, N'VIA PRINCIPE AMADEO 11', N'RIMIINI', NULL, NULL, N'3383729465', N'3383742260', 0, N'2', 0, N'STRANIERO mono - PERUVIANA - ', CAST(N'2019-10-21' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 654, N'MANE TOMAS', N'test94@gmail.com', NULL, NULL, NULL, NULL, N'VIA TURCHETTA 290', N'RIMINI', NULL, NULL, N'3389724602', N'3204647085', 0, N'1', 0, N' - ITALIANA - ', CAST(N'2020-01-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 655, N'MASINI LAURA ', N'test78@gmail.com', NULL, NULL, NULL, NULL, N'VIA MINGONI 16', N'RIMINI', NULL, NULL, N'3920802688', N'3391997559', 0, N'4', 0, N'SOSTEGNO - ITALIANA  - ', CAST(N'2019-11-20' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 656, N'MECCA FEDERICO', N'test74@gmail.com', NULL, NULL, NULL, NULL, N'VIA BIDENTE 33', N'RIMINI', NULL, NULL, N'3332352728', N'3479793079', 0, N'1', 0, N' - ITALIANO - vsilvi@libero.it', CAST(N'2019-11-12' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 657, N'MINCHILLO ASIA', N'asia.minchillo@gmail.com', NULL, NULL, NULL, NULL, N'VIA LAGOMAGGIO 139', N'RIMINI', NULL, NULL, N'3202942603', N'3889242604', 0, N'2', 0, N' - ITALIANA - pasquinacampanelli72@gmail.com', CAST(N'2019-10-24' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 658, N'MOGLI LINDA', N'test91@gmail.com', NULL, NULL, NULL, NULL, N'VIA PORDENONE 1', N'RIMINI', NULL, NULL, N'3807904801', N'3339967415', 0, N'1', 0, N' - ITALIANA - gigimogli@gmail', CAST(N'2019-12-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 659, N'MOLARI VALENTINA ', N'ctravaglini@alice.it', NULL, NULL, NULL, NULL, N'VIA SAN MARINO 139', N'SANTARCANGELO', NULL, NULL, N'3398526854', N'3394877815', 0, N'2', 0, N' - ITALIANA  - ctravaglini@alice.it', CAST(N'2019-12-20' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 660, N'MONTANARI EDOARDO', N'test109@gmail.com', NULL, NULL, NULL, NULL, N'VIA TARKOWSKIJ 7', N'RIMINI', NULL, NULL, N'3887770434', N'3381677851', 0, N'1', 0, N'DSA - ITALIANA - lietacomandini@gmail.com', CAST(N'2020-05-22' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 661, N'MORANO ALLEGRA', N'test59@gmail.com', NULL, NULL, NULL, NULL, N'VIA DEL CIGNO 2', N'RIMINI', NULL, NULL, N'3473397230', N'3331536301', 0, N'3', 0, N'DSA - ITALIANA - maddalenafabbri@gmail.com', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 662, N'MORETTI ALESSIA', N'alessiamorettiiii@gmail.com', NULL, NULL, NULL, NULL, N'VIA PRADESE N19', N'RIMINI', NULL, NULL, N'3662728559', N'3475153973', 0, N'5', 0, N' - ITALIANA - dechalle@hotmail.com', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 663, N'MORETTI ARIANNA', N'arianna.moretti@outlook.it', NULL, NULL, NULL, NULL, N'VIA BERLINGUER 25', N'RIMINI', NULL, NULL, N'3668127088', N'3297275766', 0, N'3', 0, N' - ITALIANA - mauro.more@outlook.it', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 664, N'MORETTI DAVIDE', N'test64@gmail.com', NULL, NULL, NULL, NULL, N'VIA DEL COPPO 11', N'RIMINI', NULL, NULL, N'054162143', N'3398947446', 0, N'2', 0, N'DSA - ITALIANA - lorenzasavoia@gmail.com', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 665, N'MYSENI MARI', N'test108@gmail.com', NULL, NULL, NULL, NULL, N'VIA ABBA 11', N'RIMINI', NULL, NULL, N'3278613034', N'3483515579', 0, N'1', 0, N' - ITALIANA - ', CAST(N'2020-02-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 666, N'NANNI GIANMARCO', N'nannigianmarco@gmail.com', NULL, NULL, NULL, NULL, N'VIA ZURIGO 36', N'RIMINI', NULL, NULL, N'3476630147', N'3805041707', 0, N'1', 0, N'DSA ? - ITALIANA - ', CAST(N'2019-10-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 667, N'ODDI AGNESE', N'agneseoddi', NULL, NULL, NULL, NULL, N'VIA DEI MARTIRI 21', N'RIMINI', NULL, NULL, N'3518549354', N'3405960323', 0, N'3', 0, N'SOSTEGNO - ITALIANA - antopaolizzi@gmail.com', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 668, N'PAESANI HATFULL EDOARDO', N'edoardo.paesani@gmail.com', NULL, NULL, NULL, NULL, N'VIA PEGASO 14', N'RIMINI', NULL, NULL, N'93335543135', N'3396480939', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2020-01-09' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 669, N'PAGNONI MARTINA ', N'test69@gmail.com', NULL, NULL, NULL, NULL, N'VIA BONVICINI', N'RIMINI', NULL, NULL, N'3427663166', N'3355816534', 0, N'2', 0, N'SOSTEGNO - ITALIANA - ', CAST(N'2019-11-07' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 670, N'PALLUCHINI GABRIELE', N'test57@gmail.com', NULL, NULL, NULL, NULL, N'VIA DEL GAROFANO 3', N'RIMINI', NULL, NULL, N'3805987069', N'3290799693', 0, N'5', 0, N'DSA monopare - ITALIANA - ', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 671, N'PANICO LORENZO', N'test88@gmail.com', NULL, NULL, NULL, NULL, N'VIA BIDENTE 27', N'RIMINI', NULL, NULL, N'3914800729', N'3389882525', 0, N'2', 0, N' - ITALIANA - sonia.saita75@gmail.com', CAST(N'2019-12-02' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 672, N'PARI GIAMMARIA', N'parigiammaria@gmail.com', NULL, NULL, NULL, NULL, N'VIA P. SACCHINI 20', N'RIMINI', NULL, NULL, N'3421545863', N'3283793014', 0, N'5', 0, N' - ITALIANA - ', CAST(N'2019-11-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 673, N'PASTORE MICHAEL', N'test90@gmail.com', NULL, NULL, NULL, NULL, N'VIA VISERBELLA 9', N'RIMINI', NULL, NULL, N'3703482436', N'3318796959', 0, N'1', 0, N'DSA - ITALIANA - ', CAST(N'2019-12-13' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 674, N'PERICOLI SARA ', N'test70@gmail.com', NULL, NULL, NULL, NULL, N'VIA ROBERTO ORSI 16', N'RIMINI', NULL, NULL, N'3472692311', N'3472692311', 0, N'2', 0, N' - ITALIANA  - kvega@libero.it', CAST(N'2019-11-07' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 675, N'PERROS MARTIN', N'gibellancni@gmail.com', NULL, NULL, NULL, NULL, N'VIA RENO 24', N'RIMINI', NULL, NULL, N'3339610291', N'3474225400', 0, N'5', 0, N'DSA - ITALIANA - ', CAST(N'2019-11-08' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 676, N'PIACQUADIO LEONARDO', N'test97@gmail.com', NULL, NULL, NULL, NULL, N'VIA DIAZ 26', N'RIMINI', NULL, NULL, N'3318505558', N'3392822456R', 0, N'5', 0, N'SOSTEGNO - ITALIANA - ', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 677, N'POZZI MATTEO', N'test104@gmail.com', NULL, NULL, NULL, NULL, N'VIA MARIO RENZI 4', N'RIMINI', NULL, NULL, N'3925621413', N'3393718352', 0, N'2', 0, N' - ITALIANA - bob poz@libero.it', CAST(N'2020-02-03' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 678, N'PRUDENTE MICHELE', N'test83@gmail.com', NULL, NULL, NULL, NULL, N'VIA BIZZOCCHI 11', N'RIMINI', NULL, NULL, N'3885662469', N'3291626280', 0, N'1', 0, N'SOSTEGNO - ITALIANA - saraberny@live.it', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 679, N'RIGHINI FRANCESCO ', N'test50@gmail.com', NULL, NULL, NULL, NULL, N'indirizzo', N'RIMINI', NULL, NULL, N'3505187578', N'3334004221', 0, N'1', 0, N'BES - ITALIANA - ', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 680, N'ROSA AURORA', N'test52@gmail.com', NULL, NULL, NULL, NULL, N'VIA MOSCA 27', N'RIMINI', NULL, NULL, N'3311638266', N'3339838270', 0, N'2', 0, N' - ITALIANA - nicorosa97ò@alice.it', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 681, N'ROSSETTI MARGHERITA', N'meggyrossetti@icloud.com', NULL, NULL, NULL, NULL, N'VIA MONTEFELTRO 22', N'RIMINI', NULL, NULL, N'3280023950', N'3498741618', 0, N'4', 0, N' - ITALIANA - mmfusillo@libero.it', CAST(N'2019-10-16' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 682, N'ROSSI MARTINA', N'test98@gmail.com', NULL, NULL, NULL, NULL, N'VIA ACQUABONA 3-A', N'RIMINI', NULL, NULL, N'3935290570', N'000', 0, N'5', 0, N'DSA - ITALIANA - ', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 683, N'ROSSI VALENTINA', N'valentinarossi@gmail.it', NULL, NULL, NULL, NULL, N'VIA FLAMINIA 29', N'RIMINI', NULL, NULL, N'3293866759', N'334927041', 0, N'5', 0, N'SOSTEGNO - ITALIANA - ', CAST(N'2019-10-18' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 684, N'RUSI ALAN', N'alanrusi08@gmail.com', NULL, NULL, NULL, NULL, N'VIA FRAMCESCO REDI 5', N'RIMINI', NULL, NULL, N'3425851990', N'3407210125', 0, N'2', 0, N' - ITALO-ALBANESE - milva9@gmail.com', CAST(N'2019-10-30' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 685, N'SANCHEZ VALERIA', N'margot-jeni@hotmail.com', NULL, NULL, NULL, NULL, N'VIA BELTRAMINI 32', N'RIMINI', NULL, NULL, N'3285387057', N'3801712264', 0, N'3', 0, N'BES STRAN - PERUVIANA - margot-jeni@hotmail.com', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 686, N'SAPIGLIOLI ANNA', N'annasapi03@gmail.com', NULL, NULL, NULL, NULL, N'VIA TORRICELLA FELTRIA 21', N'RIMINI', NULL, NULL, N'3913512249', N'3477963076', 0, N'3', 0, N' - ITALIANA - depa.danj@gmail.com', CAST(N'2019-10-23' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 687, N'SARTINI ALESSANDRO', N'test48@gmail.com', NULL, NULL, NULL, NULL, N'VIA MARVELLI 9', N'RIMINI', NULL, NULL, N'3890032347', N'3483927893', 0, N'2', 0, N' - ITALIANA - ', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 688, N'SCATTOLARI  NOA', N'scattolarino@gmail.com', NULL, NULL, NULL, NULL, N'VIA TURCHETTA 50', N'RIMINI', NULL, NULL, N'3314094664', N'3394805506', 0, N'2', 0, N' - ITALIANA - paolo.scattolari@vip-piva.com', CAST(N'1900-01-01' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 689, N'SENNO ALESSANDRA', N'alessandrasenno@gmail.com', NULL, NULL, NULL, NULL, N'VIA UGO BASSI 6', N'RIMINI', NULL, NULL, N'3349328661', N'3921402295', 0, N'4', 0, N'dsa - ITALIANA - stefaniagabriele@alice.it', CAST(N'2019-12-09' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 690, N'SENNO MARTINA', N'martinasenno@gmail .com', NULL, NULL, NULL, NULL, N'VIA UGO BASSI 6', N'RIMINI', NULL, NULL, N'3349328668', N'3921402295', 0, N'1', 0, N'dsa - ITALIANA - stefaniagabriele@alice.it', CAST(N'2019-12-09' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 691, N'SERGIO ALESSIA', N'alessiasergio26@gmail.com', NULL, NULL, NULL, NULL, N'V.LE OLIVETI 15-17', N'RIMINI', NULL, NULL, N'3450195328', N'3395313443', 0, N'2', 0, N' - ITALIANA - quinzimarusca@gmail.com', CAST(N'2020-02-06' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 692, N'SIMONCELLI ELISA', N'elisasimoncelli9@gmail.com', NULL, NULL, NULL, NULL, N'VIA MACANNO 140', N'RIMINI', NULL, NULL, N'3312921628', N'3402506470', 0, N'3', 0, N' - ITALIANA - cinziatamburini66@gmail.com', CAST(N'2019-10-17' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 693, N'SLIMAOUI CUMAIMA', N'test99@gmail.com', NULL, NULL, NULL, NULL, N'VIA REGINA MARGHERITA 37', N'RIMINI', NULL, NULL, N'000', N'3331782648', 0, N'5', 0, N'STRANIERA - STRANIERA - ', CAST(N'2020-01-31' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 694, N'SOLTANI AMIR', N'amyr_33@icloud.com', NULL, NULL, NULL, NULL, N'VIA DELLE CASCINE 64', N'RIMINI', NULL, NULL, N'3286304392', N'000', 0, N'5', 0, N' - ITALIANA - ', CAST(N'2019-12-03' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 695, N'SOLTANI ANIS', N'anissoltani@gmail.com', NULL, NULL, NULL, NULL, N'VIA CASCINE 6', N'RIMINI', NULL, NULL, N'3297831762', N'3341994952', 0, N'1', 0, N'S SECONDA - ITAL/TUNISINA - ', CAST(N'2019-10-15' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 696, N'TAMBURINI GABRIELE', N'test103@gmail.com', NULL, NULL, NULL, NULL, N'VIA DELLE ROSE 8', N'RIMINI', NULL, NULL, N'3347983937', N'3384555349', 0, N'3', 0, N' - ITALIANA - ', CAST(N'2020-02-03' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 697, N'TUMIDEI MATTEO', N'test87@gmail.com', NULL, NULL, NULL, NULL, N'STRADA DEL BAGELLO 84', N'SAN MARINO', NULL, NULL, N'3317789353', N'3357102259', 0, N'2', 0, N'BES - SANMARINESE - sand@libero.it', CAST(N'2019-11-20' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
INSERT [dbo].[pf_anagrafeStudenti] ([idRS], [idStudente], [nomeStud], [emailStud], [dataNascitaStud], [luogoNascitaStud], [codiceFiscaleStud], [codiceFiscaleGen], [indirizzoStud], [comuneStud], [provStud], [capStud], [tel1Stud], [tel2Stud], [idIstituto], [anno], [idSpecial], [notaStud], [dataCreate], [dataUpdate], [deleted], [privacyStud], [liberaStud], [firmaStud], [firmaDataStud], [emailCheck], [checkCode], [sediStud], [versione], [dataVersione], [idOrigineStud], [regolamentoStud]) VALUES (16, 698, N'ZANGOLI ELEONORA', N'test93@gmail.com', NULL, NULL, NULL, NULL, N'VIA POGGIOMARINO 6-D', N'RIMINI', NULL, NULL, N'3313441998', N'3496635479', 0, N'1', 0, N' - ITALIANA - bondi.elena.@gmail.com', CAST(N'2020-01-13' AS Date), CAST(N'2020-08-06' AS Date), 1, 0, 0, 0, NULL, 0, 0, N'5', N'0.0', CAST(N'2020-08-06' AS Date), 0, 0)
GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeStudenti] OFF
GO
