--USE [MSSqlProfWeb30]
--GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeProfessori] ON 
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 453, N'Becca Roberta', N'becca.roberta@alberghetti.istruzioneer.it', N'0542/24073', N'339/7502845', N'Via Tasso 6 ', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, N'', N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 454, N'Benini Franca', N'francaben@libero.it', N'0542/681751', N'348/5185024', N'Via Zara 9', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1950-11-25' AS Date), N'Imola', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 455, N'Camorani  Giorgio', N'giorgio.camorani.47@gmail.com', N'0542/29576', N'349/0620806', N'Via Linguerri 30', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1947-02-11' AS Date), N'Imola ', 1, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 456, N'Campidori Adriana', N'adrianacampidori@yahoo.it', N'0542/32294', N'339/3669034', N'Via Nardozzi 11', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1948-04-02' AS Date), N'Imola ', 1, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 457, N'Cangini Viviana', N'cleopatra5112@alice.it', N'91', N'339/8888370', N'Via Pambera 57/C', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 458, N'Casadio Loreti Egle', N'eglecl53@gmail.com', N'91', N'347/4431411', NULL, N'XXXXX', N'XX', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 459, N'Contoli Clementina', N'imolaprof8@email.com', N'0542/682370', N'338/9945046', N'Via Vivaldi 89', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 460, N'Franzini Silvia', N'silviafranzini@lamiaposta.com', N'91', N'339/7004084', N'Via C. Zampieri 3', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1944-05-21' AS Date), N'Parma', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 461, N'Genesio Anna Cira', N'annagenesio@libero.it', N'91', N'349/2906459', NULL, N'XXXXX', N'XX', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 462, N'Gentilini Pierluigi', N'pierluigi_gentilini@fastwebnet.it', N'0542/24408', N'335/8072124', N'Viale Rivalta 15', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1954-03-19' AS Date), N'Imola ', 1, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 463, N'Gianstefani Graziano', N'graziang@libero.it', N'0542/51038', N'349/4758148', N'Via Diana 3', N'Bubano/Mordano', N'BO', N'40027', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1946-11-24' AS Date), N'Mordano', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 464, N'Gonni Roberta', N'gonniroberta@gmail.com', N'0542/23035', N'338/4241272', N'Via Cerchiari 4', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 465, N'Mongardi  Monica', N'monicamongardi@yahoo.it', N'0542/012773', N'347/1650211', N'Via Pambera 4', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1949-05-03' AS Date), N'Imola', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 466, N'Perugini Daniela', N'danielaper@libero.it', N'0542/010380', N'347/2353530', N'Viale Zappi 16', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 467, N'Quarneti Renato', N'renato.quarneti@gmail.com', N'0542/32294', N'333/8262357', N'Via Villa 26', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1946-04-12' AS Date), N'Imola ', 1, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 468, N'Sassi Giambattista', N'giambattista.sassi@gmail.com', N'0542/783734', N'348/7502127', N'Via Marchesi 18', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1942-11-18' AS Date), N'Imola', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 469, N'Sgubbi Sergio', N'sgubbi@libero.it', N'0542/681751', N'348/3925733', N'Via Zara 9', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1946-10-05' AS Date), N'Imola', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 470, N'Tampieri Marino', N'ornella.marino.tampieri@gmail.com', N'0542/26339', N'340/5956186', N'Via Selice 74', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1946-07-18' AS Date), N'Imola ', 1, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 471, N'Tondini  Dania', N'imolaprof2@email.com', N'91', N'347/4538455', N'Via Zara 9', N'Imola', N'BO', N'40026', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), CAST(N'1946-10-05' AS Date), N'Imola', 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
INSERT [dbo].[pf_anagrafeProfessori] ([idRS], [idProfessore], [nomeProf], [emailProf], [tel1Prof], [tel2Prof], [indirizzoProf], [comuneProf], [provProf], [capProf], [codiceFiscaleProf], [notaProf], [dataCreate], [dataUpdate], [dataNascitaProf], [luogoNascitaProf], [idTipoSocioProf], [idTipoProf], [deleted], [privacyProf], [liberaProf], [firmaProf], [firmaDataProf], [emailCheck], [checkCode], [sediProf], [materiaProf], [lezioniPrenotate], [versione], [dataVersione]) VALUES (17, 472, N'Voltan Elisa', N'elisa.voltan1945@gmail.com', N'91', N'346/3126425', NULL, N'XXXXX', N'XX', N'0', NULL, NULL, CAST(N'2020-09-09' AS Date), CAST(N'2020-09-09' AS Date), NULL, NULL, 0, 0, 1, 0, 0, 0, NULL, 0, 0, N'6', NULL, NULL, N'0.0', CAST(N'2020-09-09' AS Date))
GO
SET IDENTITY_INSERT [dbo].[pf_anagrafeProfessori] OFF
GO
